name: Documentation Issue
description: Report issues in our documentation
title: "[Documentation]: <Title>"
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: We appreciate you taking the time to submit your documentation issue.
  - type: checkboxes
    id: preliminary_actions
    attributes:
      label: Preliminary Actions
      options:
      - label: I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: dropdown
    id: driver_type
    attributes:
      label: Driver Type
      description: What driver type are you running?
      options:
        - Linux kernel driver for Elastic Network Adapter (ENA)
        - FreeBSD kernel driver for Elastic Network Adapter (ENA)
        - DPDK PMD for Elastic Network Adapter (ENA)
        - Linux kernel driver for Elastic Fabric Adapter (EFA)
    validations:
      required: true
  - type: input
    id: driver_tag
    attributes:
      label: Driver Tag/Commit
      placeholder: "ena_linux_2.8.3"
      description: |
        You can check current driver tag/commit using "git describe --tags"
        Please test using the latest version to make sure your issue has not already been fixed
    validations:
      required: true
  - type: textarea
    id: documentation_description
    attributes:
      label: Documentation issue description
      placeholder: Describe the documentation issue in detail
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://aws.amazon.com/codeofconduct/)
      options:
        - label: I agree to follow AWS Code of Conduct
    validations:
      required: true
